interface User {
  id: number
  firstName: string
  lastName: string
  role: string
  facility: string
  council: string
  system?: string
}

export const users = <User[]>[
  {
    id: 1,
    firstName: 'Fatuma',
    lastName: 'Juma',
    role: 'CHW',
    facility: 'Kisarawe Dispensary',
    council: 'Kisarawe',
    system: 'openmrs',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'Mbwana',
    role: 'CHW',
    facility: 'Mlandizi Health Center',
    council: 'Bagamoyo',
    system: 'openmrs',
  },
  {
    id: 3,
    firstName: 'Asha',
    lastName: 'Selemani',
    role: 'CHW',
    facility: 'Kigamboni Clinic',
    council: 'Kigamboni',
    system: 'openmrs',
  },
  {
    id: 4,
    firstName: 'Peter',
    lastName: 'Maganga',
    role: 'COUNCIL',
    facility: 'Temeke Municipal',
    council: 'Temeke',
    system: 'dhis',
  },
  {
    id: 5,
    firstName: 'Mary',
    lastName: 'Joseph',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 6,
    firstName: 'Ahmed',
    lastName: 'Hassan',
    role: 'CHW',
    facility: 'Mkuranga Dispensary',
    council: 'Mkuranga',
    system: 'openmrs',
  },
  {
    id: 7,
    firstName: 'Zahra',
    lastName: 'Omar',
    role: 'SYS_DEV',
    facility: 'ICT Office',
    council: 'HQ',
    system: 'manager',
  },
  {
    id: 8,
    firstName: 'Neema',
    lastName: 'Shabani',
    role: 'CHW',
    facility: 'Mbagala Health Center',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 9,
    firstName: 'Joseph',
    lastName: 'Mwanjela',
    role: 'CHW',
    facility: 'Tegeta Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 10,
    firstName: 'Mwajuma',
    lastName: 'Saidi',
    role: 'PROVIDER',
    facility: 'Magomeni Hospital',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 11,
    firstName: 'Salum',
    lastName: 'Abdallah',
    role: 'CHW',
    facility: 'Tandika Dispensary',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 12,
    firstName: 'Agnes',
    lastName: 'Lema',
    role: 'CHW',
    facility: 'Kigogo Health Center',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 13,
    firstName: 'Frank',
    lastName: 'Mushi',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 14,
    firstName: 'Rehema',
    lastName: 'Ali',
    role: 'CHW',
    facility: 'Buguruni Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 15,
    firstName: 'Yusuph',
    lastName: 'Bakari',
    role: 'CHW',
    facility: 'Kimara Health Center',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 16,
    firstName: 'Grace',
    lastName: 'Ndalu',
    role: 'PROVIDER',
    facility: 'Amana Hospital',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 17,
    firstName: 'Hamis',
    lastName: 'Mussa',
    role: 'CHW',
    facility: 'Chang’ombe Clinic',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 18,
    firstName: 'Beatrice',
    lastName: 'Mhando',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 19,
    firstName: 'Fatma',
    lastName: 'Rajabu',
    role: 'CHW',
    facility: 'Segerea Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 20,
    firstName: 'Oscar',
    lastName: 'Komba',
    role: 'CHW',
    facility: 'Mbezi Health Center',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 21,
    firstName: 'Joyce',
    lastName: 'Mwakalinga',
    role: 'CHW',
    facility: 'Ubungo Clinic',
    council: 'Ubungo',
    system: 'openmrs',
  },
  {
    id: 22,
    firstName: 'Martha',
    lastName: 'Mwanri',
    role: 'CHW',
    facility: 'Kawe Health Center',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 23,
    firstName: 'Saidi',
    lastName: 'Kassim',
    role: 'PROVIDER',
    facility: 'Sinza Hospital',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 24,
    firstName: 'Nasra',
    lastName: 'Omary',
    role: 'CHW',
    facility: 'Majohe Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 25,
    firstName: 'Jackson',
    lastName: 'Mwita',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 26,
    firstName: 'Anna',
    lastName: 'Ndunguru',
    role: 'CHW',
    facility: 'Goba Health Center',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 27,
    firstName: 'Paul',
    lastName: 'Chacha',
    role: 'CHW',
    facility: 'Mwananyamala Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 28,
    firstName: 'Halima',
    lastName: 'Mohamed',
    role: 'CHW',
    facility: 'Tabata Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 29,
    firstName: 'Erick',
    lastName: 'Masanja',
    role: 'PROVIDER',
    facility: 'Muhimbili Hospital',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 30,
    firstName: 'Ester',
    lastName: 'George',
    role: 'CHW',
    facility: 'Makumbusho Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 31,
    firstName: 'Mariam',
    lastName: 'Ramadhani',
    role: 'CHW',
    facility: 'Vingunguti Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 32,
    firstName: 'Lucas',
    lastName: 'Gervas',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 33,
    firstName: 'Sarah',
    lastName: 'Mgaya',
    role: 'CHW',
    facility: 'Kurasini Clinic',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 34,
    firstName: 'Daniel',
    lastName: 'Nyangoma',
    role: 'CHW',
    facility: 'Bunju Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 35,
    firstName: 'Zuhura',
    lastName: 'Haji',
    role: 'CHW',
    facility: 'Yombo Health Center',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 36,
    firstName: 'Michael',
    lastName: 'Katala',
    role: 'PROVIDER',
    facility: 'Regency Hospital',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 37,
    firstName: 'Sophia',
    lastName: 'Mkude',
    role: 'CHW',
    facility: 'Makumbusho Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 38,
    firstName: 'Tatu',
    lastName: 'Kassim',
    role: 'CHW',
    facility: 'Pugu Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 39,
    firstName: 'Paschal',
    lastName: 'Mapunda',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 40,
    firstName: 'Leah',
    lastName: 'Ngowi',
    role: 'CHW',
    facility: 'Msasani Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 41,
    firstName: 'Juma',
    lastName: 'Kassim',
    role: 'CHW',
    facility: 'Kariakoo Clinic',
    council: 'Ilala',
    system: 'openmrs',
  },
  {
    id: 42,
    firstName: 'Amina',
    lastName: 'Mussa',
    role: 'PROVIDER',
    facility: 'Mwananyamala Hospital',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 43,
    firstName: 'Hassan',
    lastName: 'Juma',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 44,
    firstName: 'Fatuma',
    lastName: 'Ali',
    role: 'CHW',
    facility: 'Kigogo Clinic',
    council: 'Kinondoni',
    system: 'openmrs',
  },
  {
    id: 45,
    firstName: 'Peter',
    lastName: 'John',
    role: 'SYS_DEV',
    facility: 'ICT Office',
    council: 'HQ',
    system: 'manager',
  },
  {
    id: 46,
    firstName: 'Mary',
    lastName: 'Maganga',
    role: 'CHW',
    facility: 'Mbagala Clinic',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 47,
    firstName: 'Ahmed',
    lastName: 'Omar',
    role: 'PROVIDER',
    facility: 'Temeke Hospital',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 48,
    firstName: 'Zahra',
    lastName: 'Hassan',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 49,
    firstName: 'Neema',
    lastName: 'Juma',
    role: 'CHW',
    facility: 'Mkuranga Clinic',
    council: 'Mkuranga',
    system: 'openmrs',
  },
  {
    id: 50,
    firstName: 'Joseph',
    lastName: 'Mbwana',
    role: 'SYS_DEV',
    facility: 'ICT Office',
    council: 'HQ',
    system: 'manager',
  },
  {
    id: 51,
    firstName: 'Mwajuma',
    lastName: 'Selemani',
    role: 'CHW',
    facility: 'Kisarawe Clinic',
    council: 'Kisarawe',
    system: 'openmrs',
  },
  {
    id: 52,
    firstName: 'Salum',
    lastName: 'Maganga',
    role: 'PROVIDER',
    facility: 'Mlandizi Hospital',
    council: 'Bagamoyo',
    system: 'openmrs',
  },
  {
    id: 53,
    firstName: 'Agnes',
    lastName: 'Joseph',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 54,
    firstName: 'Frank',
    lastName: 'Hassan',
    role: 'CHW',
    facility: 'Kigamboni Clinic',
    council: 'Kigamboni',
    system: 'openmrs',
  },
  {
    id: 55,
    firstName: 'Rehema',
    lastName: 'Omar',
    role: 'PROVIDER',
    facility: 'Temeke Hospital',
    council: 'Temeke',
    system: 'openmrs',
  },
  {
    id: 56,
    firstName: 'Yusuph',
    lastName: 'Shabani',
    role: 'MOH',
    facility: 'Ministry of Health',
    council: 'HQ',
    system: 'dhis',
  },
  {
    id: 57,
    firstName: 'Grace',
    lastName: 'Mwanjela',
    role: 'CHW',
    facility: 'Mkuranga Clinic',
    council: 'Mkuranga',
    system: 'openmrs',
  },
]
